USE quizdb;

INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_option) VALUES
("What is the capital of India?", "Mumbai", "New Delhi", "Kolkata", "Chennai", "B"),
("Which is the smallest continent?", "Africa", "Europe", "Australia", "South America", "C"),
("Who invented the light bulb?", "Einstein", "Newton", "Edison", "Tesla", "C"),
("What is the square root of 64?", "6", "8", "7", "9", "B"),
("Which element has the symbol 'O'?", "Gold", "Oxygen", "Osmium", "Oxide", "B"),
("In which year did India gain independence?", "1942", "1947", "1950", "1935", "B"),
("What is the currency of Japan?", "Yuan", "Yen", "Won", "Dollar", "B"),
("Which language is used to build web pages?", "HTML", "Python", "C++", "Java", "A"),
("Which organ pumps blood in human body?", "Brain", "Lungs", "Heart", "Liver", "C"),
("Which planet has rings?", "Mars", "Saturn", "Venus", "Mercury", "B"),
("Which animal is known as 'King of Jungle'?", "Tiger", "Elephant", "Lion", "Leopard", "C"),
("Who is the father of computers?", "Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs", "A"),
("Which vitamin comes from sunlight?", "A", "B", "C", "D", "D"),
("Which country hosted Olympics 2020?", "Japan", "China", "India", "Brazil", "A"),
("Which bird is the symbol of peace?", "Crow", "Pigeon", "Dove", "Sparrow", "C"),
("Which gas is used in balloons?", "Hydrogen", "Helium", "Oxygen", "Nitrogen", "B"),
("What does CPU stand for?", "Central Power Unit", "Central Processing Unit", "Computer Power Unit", "Computer Process Unit", "B"),
("Which is the fastest land animal?", "Cheetah", "Lion", "Horse", "Leopard", "A"),
("Which festival is called festival of lights?", "Eid", "Christmas", "Diwali", "Holi", "C"),
("Which is the national fruit of India?", "Banana", "Apple", "Mango", "Grapes", "C"),
("Which planet is closest to the sun?", "Earth", "Venus", "Mars", "Mercury", "D"),
("What is the largest bone in human body?", "Skull", "Femur", "Spine", "Tibia", "B"),
("Which is the longest river in the world?", "Nile", "Amazon", "Ganga", "Yangtze", "A"),
("What is 10 x 10?", "100", "90", "110", "120", "A"),
("Who wrote 'Harry Potter'?", "Tolkien", "Rowling", "Lewis", "Martin", "B"),
("Which planet is called Earth’s twin?", "Venus", "Mars", "Mercury", "Neptune", "A"),
("Which is a leap year?", "2021", "2023", "2020", "2019", "C"),
("What is the capital of Kerala?", "Kochi", "Kannur", "Thiruvananthapuram", "Calicut", "C"),
("Which is the national animal of India?", "Elephant", "Lion", "Tiger", "Peacock", "C"),
("What is H2SO4?", "Hydrochloric Acid", "Sulphuric Acid", "Acetic Acid", "Nitric Acid", "B"),
("How many states are there in India?", "29", "28", "27", "30", "B"),
("Which is the smallest prime number?", "1", "2", "3", "0", "B"),
("Which organ helps in breathing?", "Lungs", "Heart", "Liver", "Kidney", "A"),
("Which planet is known for its red appearance?", "Mars", "Earth", "Uranus", "Neptune", "A"),
("Which programming language is known for AI?", "C", "Python", "PHP", "Java", "B"),
("What is the capital of Tamil Nadu?", "Madurai", "Salem", "Chennai", "Coimbatore", "C"),
("Which is the national bird of India?", "Pigeon", "Sparrow", "Peacock", "Owl", "C"),
("What is 50 ÷ 5?", "5", "10", "15", "20", "B"),
("Which part of the plant makes food?", "Root", "Stem", "Leaf", "Flower", "C"),
("What is the freezing point of water?", "0°C", "100°C", "25°C", "50°C", "A"),
("What is the capital of USA?", "New York", "Washington D.C.", "Los Angeles", "Chicago", "B"),
("Which shape has three sides?", "Square", "Triangle", "Circle", "Rectangle", "B"),
("How many legs does a spider have?", "6", "8", "4", "10", "B"),
("Which metal is liquid at room temperature?", "Iron", "Mercury", "Aluminum", "Gold", "B"),
("What is the chemical formula for salt?", "NaCl", "KCl", "HCl", "CaCl2", "A"),
("What color do you get by mixing red and yellow?", "Green", "Orange", "Blue", "Purple", "B"),
("How many players in a cricket team?", "10", "11", "12", "9", "B"),
("Which festival involves colors?", "Eid", "Christmas", "Holi", "Diwali", "C"),
("Which country is called Land of Rising Sun?", "India", "China", "Japan", "Thailand", "C");
